spring:
  cloud:
    alicloud:
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket: gulimall06
      access-key: LTAI5tJNpsqYmLRnD5jSkPNZ
      secret-key: Y6g4F3NrNNJ9rgTwoltUAnRg3tviUo

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-third-party
server:
  port: 30000


